"""Initial migration

Revision ID: 3f4ca60bd9d9
Revises: 
Create Date: 2025-05-25 17:33:59.255243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4ca60bd9d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('flags_found',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(length=128), nullable=False),
    sa.Column('lab_name', sa.String(length=64), nullable=False),
    sa.Column('flag_type', sa.String(length=32), nullable=True),
    sa.Column('found_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flags_found')
    op.drop_table('users')
    # ### end Alembic commands ###
